---
- name: Create group {{ user }}
  group: name={{ user }} system=yes

- name: Install virtualenv (Python 2)
  apt: name=python-virtualenv

- name: Install virtualenv (Python 3)
  apt: name=python3-virtualenv

- name: Install virtualenv
  apt: name=virtualenv

# Workaround for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=766867

- name: Install python-dev (for compiling gevent)
  apt: name="{{ python }}-dev"
  when: ansible_distribution_release == 'jessie'

- name: Upgrade pip (for installing the binary of gevent)
  pip:
    name: pip
    version: 8.1.2
    virtualenv: "{{ virtualenv }}"
    virtualenv_site_packages: yes
    virtualenv_python: "{{ python }}"
  when: python == "python3"

- name: Install gevent from source
  pip:
    name: gevent
    version: '{% if python == "python3" %}1.1.1{% else %}1.0.2{% endif %}'
    virtualenv: "{{ virtualenv }}"
    virtualenv_site_packages: yes
    virtualenv_python: "{{ python }}"
  when: ansible_distribution_release == 'jessie'

# End workaround


- name: Create user {{ user }}
  user:
    name: "{{ user }}"
    group: "{{ user }}"
    system: yes

- name: Create {{ instance_name }} configuration directory
  file: name={{ config_dir }} state=directory

- name: Create {{ instance_name }} log directory
  file:
    name: "{{ log_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Create gunicorn {{ instance_name }} log file
  command: >
    touch {{ log_dir }}/{{ instance_name }}.log
    creates={{ log_dir }}/{{ instance_name }}.log

- name: Ensure {{ log_dir }}/{{ instance_name }}.log has correct permissions
  file:
    name: "{{ log_dir }}/{{ instance_name }}.log"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Install gunicorn
  pip:
    name: gunicorn
    virtualenv: "{{ virtualenv }}"
    virtualenv_site_packages: yes
    virtualenv_python: "{{ python }}"

- name: Configure gunicorn
  template:
    src: run-gunicorn
    dest: "{{ config_dir }}/run-gunicorn"
    mode: 0755
  notify:
  - Restart {{ instance_name }}

- name: Configure supervisor
  template:
    src: supervisor.conf
    dest: /etc/supervisor/conf.d/{{ program_name }}-{{ instance_name }}.conf
  notify:
  - Restart {{ instance_name }}
